const constants = {
    gatewayBaseUrl: "wss://gateway.discord.gg",
    gatewayVersion: 10,
    gatewayEncoding: "json",
    apiBaseUrl: "https://discord.com/api",
    apiVersion: 10,
    voiceGatewayVersion: 8,
    intents: {
        // https://discord.com/developers/docs/events/gateway#list-of-intents
        GUILDS: 1 << 0,
        GUILD_MEMBERS: 1 << 1,
        GUILD_MODERATION: 1 << 2,
        GUILD_EXPRESSIONS: 1 << 3,
        GUILD_INTEGRATIONS: 1 << 4,
        GUILD_WEBHOOKS: 1 << 5,
        GUILD_INVITES: 1 << 6,
        GUILD_VOICE_STATES: 1 << 7,
        GUILD_PRESENCES: 1 << 8,
        GUILD_MESSAGES: 1 << 9,
        GUILD_MESSAGE_REACTIONS: 1 << 10,
        GUILD_MESSAGE_TYPING: 1 << 11,
        DIRECT_MESSAGES: 1 << 12,
        DIRECT_MESSAGE_REACTIONS: 1 << 13,
        DIRECT_MESSAGE_TYPING: 1 << 14,
        MESSAGE_CONTENT: 1 << 15,
        GUILD_SCHEDULED_EVENTS: 1 << 16,
        AUTO_MODERATION_CONFIGURATION: 1 << 20,
        AUTO_MODERATION_EXECUTION: 1 << 21,
        GUILD_MESSAGE_POLLS: 1 << 24,
        DIRECT_MESSAGE_POLLS: 1 << 25,
    },
    gatewayOpcodes: {
        DISPATCH: 0,
        HEARTBEAT: 1,
        IDENTIFY: 2,
        PRESENCE_UPDATE: 3,
        VOICE_STATE_UPDATE: 4,
        RESUME: 6,
        RECONNECT: 7,
        REQUEST_GUILD_MEMBERS: 8,
        INVALID_SESSION: 9,
        HELLO: 10,
        HEARTBEAT_ACK: 11,
        REQUEST_SOUNDBOARD_SOUNDS: 31
    },
    voiceGatewayOpcodes: {
        IDENTIFY: 0,
        SELECT_PROTOCOL: 1,
        READY: 2,
        HEARTBEAT: 3,
        SESSION_DESCRIPTION: 4,
        SPEAKING: 5,
        HEARTBEAT_ACK: 6,
        RESUME: 7,
        HELLO: 8,
        RESUMED: 9,
        CLIENTS_CONNECT: 10,
        CLIENT_DISCONNECT: 13,
        // TODO: DAVE opcodes
        
    },
    defaultVoiceMode: "aead_aes256_gcm_rtpsize",
    allowedVoiceModes: ["aead_aes256_gcm_rtpsize", "aead_xchacha20_poly1305_rtpsize"],
    channelTypes: {
        GUILD_TEXT: 0,
        DM: 1,
        GUILD_VOICE: 2,
        GROUP_DM: 3,
        GUILD_CATEGORY: 4,
        GUILD_ANNOUNCEMENT: 5,
        ANNOUNCEMENT_THREAD: 10,
        PUBLIC_THREAD: 11,
        PRIVATE_THREAD: 12,
        GUILD_STAGE_VOICE: 13,
        GUILD_DIRECTORY: 14,
        GUILD_FORUM: 15,
        GUILD_MEDIA: 16,
    },
    channelVoiceTypes: [
        "GUILD_VOICE"
    ],
    readyTimeout: 5000,
    timeout: 5000,
    gatewayReconnectTimeout: 1000
};

module.exports = constants;