module.exports = {
    IdentifyParser: require("./parsers/IdentifyParser"),
    VoiceServerUpdateParser: require("./parsers/VoiceServerUpdateParser"),
    VoiceStateParser: require("./parsers/VoiceStateParser"),
    VoiceStateUpdateParser: require("./parsers/VoiceStateUpdateParser"),
    UserParser: require("./parsers/UserParser"),
    ChannelParser: require("./parsers/ChannelParser"),
    GuildParser: require("./parsers/GuildParser"),
    // GuildMemberParser: require("./parsers/GuildMemberParser"),
    ReadyParser: require("./parsers/ReadyParser"),
    VoiceReadyParser: require("./parsers/VoiceReadyParser"),
    MessageParser: require("./parsers/MessageParser"),
    SessionDescriptionParser: require("./parsers/SessionDescriptionParser"),
    VoiceIdentifyParser: require("./parsers/VoiceIdentifyParser"),
    SelectProtocolParser: require("./parsers/SelectProtocolParser"),
    SpeakingParser: require("./parsers/SpeakingParser"),
};